FROM python:3.10

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y cmake autoconf automake g++ libtool make

COPY pip.conf /root/.config/pip/pip.conf

WORKDIR /code

COPY . /code/.

RUN pip install --no-cache-dir -e .
RUN pip install --no-cache-dir -e ".[nl2ltl]"
RUN ls
RUN chmod +x scripts/build-submodules.sh
RUN scripts/build-submodules.sh


EXPOSE 8000
CMD ["uvicorn", "server.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]