version: '3' # specify docker-compose version

services:
  frontend:
    build: 
      context: ./
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    depends_on:
      - "backend"

  backend:
    build:
      context: ./
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}

networks:
  mynetwork: